<?php
$company = $settings['company_name'] ?? 'شبکه پردازان ایده‌بان الماس';
$phone = $settings['phone'] ?? '09104927131';
$tel = preg_replace('/[^0-9+]/', '', $phone) ?: '09104927131';
?>
<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="<?= e(site_url('/')) ?>">خانه</a> / تماس و مشاوره</div><div class="eyebrow"><span class="dot"></span> درخواست مشاوره یا پیش‌فاکتور</div><h1>نیاز فناوری کسب‌وکارتان را مطرح کنید</h1><p>فرم زیر را تکمیل کنید. درخواست در سامانه ثبت می‌شود تا برای پیگیری و نیازسنجی با شما تماس گرفته شود.</p></div></section>
<section class="contact-section" id="contact"><div class="container contact-grid">
<div class="contact-copy"><div class="section-kicker">ارتباط با <?= e($company) ?></div><h2>اول نیاز را می‌فهمیم، بعد راهکار پیشنهاد می‌دهیم</h2><p>شرح کوتاهی از مسئله، وضعیت فعلی یا هدف پروژه بنویسید. اطلاعات حساس، رمز عبور یا کلیدهای دسترسی را در این فرم ارسال نکنید.</p><div class="contact-details"><div class="contact-detail"><span class="detail-icon"><svg viewBox="0 0 24 24" fill="none"><path d="M6.5 3.5h3L11 8l-2 1.5a15 15 0 0 0 5.5 5.5L16 13l4.5 1.5v3c0 1.1-.9 2-2 2A15 15 0 0 1 4.5 5.5c0-1.1.9-2 2-2Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/></svg></span><span><small>تماس مستقیم</small><a href="tel:<?= e($tel) ?>" dir="ltr"><?= e($phone) ?></a></span></div><div class="contact-detail"><span class="detail-icon"><svg viewBox="0 0 24 24" fill="none"><path d="M12 21s7-6.1 7-12a7 7 0 1 0-14 0c0 5.9 7 12 7 12Z" stroke="currentColor" stroke-width="1.6"/><circle cx="12" cy="9" r="2.3" stroke="currentColor" stroke-width="1.6"/></svg></span><span><small>محدوده اجرای حضوری</small>پس از بررسی و توافق</span></div></div></div>
<form class="contact-form" action="<?= e(site_url('/request-quote')) ?>" method="post">
<?= csrf_field() ?><input type="hidden" name="lead_type" value="quote"><input type="hidden" name="source" value="<?= e($leadSource ?? 'website') ?>"><div class="honeypot" aria-hidden="true"><label>وب‌سایت<input type="text" name="website" tabindex="-1" autocomplete="off"></label></div>
<div class="form-grid"><div class="field"><label for="full_name">نام و نام خانوادگی *</label><input id="full_name" name="full_name" type="text" required maxlength="160" autocomplete="name"></div><div class="field"><label for="phone">شماره تماس *</label><input id="phone" name="phone" type="tel" required maxlength="32" autocomplete="tel" dir="ltr"></div><div class="field"><label for="company_name">نام شرکت</label><input id="company_name" name="company_name" type="text" maxlength="180" autocomplete="organization"></div><div class="field"><label for="email">ایمیل</label><input id="email" name="email" type="email" maxlength="190" autocomplete="email" dir="ltr"></div><div class="field full"><label for="service_id">خدمت موردنیاز</label><select id="service_id" name="service_id"><option value="0">انتخاب یا استعلام خدمت</option><?php foreach ($services as $service): ?><option value="<?= (int) $service['id'] ?>"><?= e($service['title']) ?></option><?php endforeach; ?></select><input type="hidden" name="requested_service" value=""></div><div class="field full"><label for="description">شرح نیاز یا مسئله</label><textarea id="description" name="description" maxlength="8000" placeholder="هدف، وضعیت فعلی، امکانات موردنیاز یا محدودیت زمانی را توضیح دهید."></textarea></div></div>
<div class="form-footer"><label class="privacy-note"><input type="checkbox" name="privacy_consent" value="1" required> با استفاده از اطلاعات تماس برای پیگیری درخواست موافقم.</label><button class="btn btn-primary" type="submit">ثبت درخواست و نیازسنجی <svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M4 10h12m0 0-5-5m5 5-5 5" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div>
</form>
</div></section>
