<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="<?= e(site_url('/')) ?>">خانه</a> / پلن‌ها و تعرفه‌ها</div><div class="eyebrow"><span class="dot"></span> پلن‌های همکاری</div><h1>چارچوب‌های روشن برای شروع گفت‌وگو</h1><p>پلن‌ها برای مقایسه سطح نیاز طراحی شده‌اند. محدوده نهایی و قیمت هر خدمت پس از نیازسنجی و بررسی موارد وابسته مشخص می‌شود.</p></div></section>
<section class="section section-soft"><div class="container">
<div class="plans-grid">
<?php foreach ($plans as $plan): ?>
  <article class="plan-card <?= !empty($plan['is_featured']) ? 'featured' : '' ?>"><?php if (!empty($plan['is_featured'])): ?><span class="plan-badge">پیشنهادی</span><?php endif; ?><div class="plan-type"><?= e($plan['audience']) ?></div><h3><?= e($plan['title']) ?></h3><p><?= e($plan['summary']) ?></p><?php $currentPriceInfo = $plan['price_info'] ?? []; require APP_ROOT . '/app/Views/partials/price-info.php'; ?><ul class="plan-list"><?php foreach ($plan['features'] ?? [] as $feature): ?><li><svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m4 10 4 4 8-8" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg><?= e($feature['feature_text']) ?></li><?php endforeach; ?></ul><a class="btn <?= !empty($plan['is_featured']) ? 'btn-dark' : 'btn-outline' ?>" href="<?= e(site_url('/contact#contact')) ?>">درخواست پیش‌فاکتور</a></article>
<?php endforeach; ?>
<?php if ($plans === []): ?><div class="empty-state">پلن‌ها در حال تکمیل هستند. برای دریافت برآورد، درخواست مشاوره ثبت کنید.</div><?php endif; ?>
</div>
<div class="section-heading section-heading-spaced"><div><div class="section-kicker">اصول نمایش تعرفه</div><h2>شفافیت قیمت، بدون نرخ‌سازی</h2></div><p>تعرفه رسمی ۱۴۰۵ فقط همراه منبع و وضعیت تأییدشده منتشر می‌شود. قیمت پیشنهادی شرکت، قیمت توافقی و خدمات نیازمند برآورد جداگانه مشخص می‌شوند.</p></div>
<div class="services-grid"><article class="service-card"><div class="section-kicker">رسمی</div><h3>تعرفه رسمی تأییدشده</h3><p>همراه با منبع، واحد محاسبه، تاریخ اعتبار و سال تعرفه.</p></article><article class="service-card"><div class="section-kicker">پیشنهادی</div><h3>قیمت پیشنهادی شرکت</h3><p>قابل به‌روزرسانی و جدا از تعرفه رسمی؛ جزئیات در پیش‌فاکتور مشخص می‌شود.</p></article><article class="service-card"><div class="section-kicker">توافقی</div><h3>نیازمند برآورد</h3><p>برای خدمات سفارشی یا وابسته به شرایط پروژه، درخواست استعلام ثبت کنید.</p></article></div>
<p class="plan-footnote">مبالغ در صورت ثبت‌شدن، به تومان هستند. اعتبار قیمت و هزینه‌های جانبی در پیش‌فاکتور درج می‌شود.</p>
</div></section>
