<?php
$includes = preg_split('/\r\n|\r|\n|;|؛/', (string) ($service['scope_includes'] ?? '')) ?: [];
$includes = array_values(array_filter(array_map('trim', $includes)));
$excludes = preg_split('/\r\n|\r|\n|;|؛/', (string) ($service['scope_excludes'] ?? '')) ?: [];
$excludes = array_values(array_filter(array_map('trim', $excludes)));
?>
<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="<?= e(site_url('/')) ?>">خانه</a> / <a href="<?= e(site_url('/services')) ?>">خدمات</a> / <?= e($service['title']) ?></div><div class="eyebrow"><span class="dot"></span> <?= e($service['category_title']) ?></div><h1><?= e($service['title']) ?></h1><p><?= e($service['short_description']) ?></p></div></section>
<section class="section"><div class="container two-col"><div class="value-copy"><div class="section-kicker">درباره خدمت</div><h2>راهکاری متناسب با مسئله شما</h2><p><?= nl2br(e($service['description'] ?? $service['short_description'])) ?></p><?php $currentPriceInfo = $priceInfo ?? []; $priceContainerClass = 'service-price'; require APP_ROOT . '/app/Views/partials/price-info.php'; ?><p>زمان اجرا و اقلام تحویلی پس از بررسی نیازمندی‌ها و تعیین محدوده، در پیشنهاد یا پیش‌فاکتور اعلام می‌شوند.</p><a class="btn btn-dark" href="<?= e(site_url('/contact#contact')) ?>">درخواست پیش‌فاکتور</a></div><div class="value-visual"><div class="value-center"><svg viewBox="0 0 32 32" fill="none"><path d="M16 2.8 28.5 10v12L16 29.2 3.5 22V10L16 2.8Z" stroke="currentColor" stroke-width="1.8"/><path d="m16 8.5 7.5 4.3v6.4L16 23.5l-7.5-4.3v-6.4L16 8.5Z" stroke="currentColor" stroke-width="1.4"/></svg><b>راهکار تخصصی</b></div><span class="value-node node-a">نیازسنجی</span><span class="value-node node-b">طراحی</span><span class="value-node node-c">اجرا</span><span class="value-node node-d">پشتیبانی</span></div></div></section>
<section class="section section-soft"><div class="container"><div class="section-heading"><div><div class="section-kicker">محدوده همکاری</div><h2>چه مواردی در بررسی قرار می‌گیرند؟</h2></div><p><?= e($service['delivery_note'] ?? 'محدوده، زمان و هزینه پس از بررسی نیازمندی‌ها اعلام می‌شود.') ?></p></div><div class="services-grid"><article class="service-card"><div class="section-kicker">موارد قابل توافق</div><h3>شامل خدمت</h3><p><?= $includes ? nl2br(e(implode("\n", $includes))) : 'اقلام تحویلی در زمان نیازسنجی و پیش از شروع پروژه مشخص می‌شوند.' ?></p></article><article class="service-card"><div class="section-kicker">شفافیت محدوده</div><h3>هزینه‌های جانبی</h3><p><?= $excludes ? nl2br(e(implode("\n", $excludes))) : 'هزینه میزبانی، دامنه، تجهیزات، مجوزها یا سرویس‌های ثالث در صورت نیاز جداگانه بررسی می‌شوند.' ?></p></article><article class="service-card"><div class="section-kicker">قیمت‌گذاری</div><h3>روش برآورد</h3><p>قیمت این خدمت پس از بررسی جزئیات و شرایط اجرا اعلام می‌شود. تعرفه رسمی فقط با منبع معتبر و تأییدشده نمایش داده خواهد شد.</p><a class="service-link" href="<?= e(site_url('/pricing')) ?>">دیدن پلن‌ها</a></article></div></div></section>
<?php if (!empty($plans)): ?><section class="section"><div class="container"><div class="section-heading"><div><div class="section-kicker">پلن‌های مرتبط</div><h2>راهکار را با محدوده مناسب انتخاب کنید</h2></div><p>پلن‌ها چارچوب اولیه هستند؛ محدوده و قیمت نهایی پس از بررسی نیاز مشخص می‌شود.</p></div><div class="listing-grid"><?php foreach ($plans as $plan): ?><article class="content-card"><span class="section-kicker"><?= e($plan['audience']) ?></span><h3><?= e($plan['title']) ?></h3><p><?= e($plan['summary']) ?></p><a class="text-link" href="<?= e(site_url('/contact#contact')) ?>">درخواست برآورد</a></article><?php endforeach; ?></div></div></section><?php endif; ?>
<section class="section"><div class="container"><div class="portfolio-empty"><div class="empty-art" aria-hidden="true"><svg viewBox="0 0 36 36" fill="none"><path d="M5 11h26v19H5zM5 16h26M11 7h14" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/><path d="m13 23 3 3 7-7" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div><h3>قدم بعدی: تعریف نیاز و دریافت برآورد</h3><p>با ارسال درخواست، خدمت موردنیاز و شرایط اجرایی با شما بررسی می‌شود.</p></div><a class="btn btn-primary" href="<?= e(site_url('/contact#contact')) ?>">ثبت درخواست</a></div></div></section>
